### ISSUE TITLE
Error occurred while running the project using Docker

### ISSUE THREAD

**Issue by RuiqiYing** [ika-rwth-aachen/Point-Cloud-Compression#4]
Hello , author.
Thank you for your excellent open-source work.
I encountered some issues while running the project using Docker, and the following error message appeared:

sudo ./docker_train.sh
Traceback (most recent call last):
File "/src/range_image_compression/train.py", line 31, in
from utils import load_config_and_model
File "/src/range_image_compression/utils.py", line 28, in
from architectures import Additive_LSTM_Demo, Additive_LSTM, Additive_LSTM_Slim, Additive_GRU, Oneshot_LSTM
File "/src/range_image_compression/architectures/Oneshot_LSTM.py", line 30, in
import tensorflow_compression as tfc
File "/usr/local/lib/python3.8/dist-packages/tensorflow_compression/init.py", line 17, in
from tensorflow_compression.python import distributions
File "/usr/local/lib/python3.8/dist-packages/tensorflow_compression/python/distributions/init.py", line 17, in
from tensorflow_compression.python.distributions.deep_factorized import *
File "/usr/local/lib/python3.8/dist-packages/tensorflow_compression/python/distributions/deep_factorized.py", line 18, in
import tensorflow_probability as tfp
File "/usr/local/lib/python3.8/dist-packages/tensorflow_probability/init.py", line 20, in
from tensorflow_probability import substrates
File "/usr/local/lib/python3.8/dist-packages/tensorflow_probability/substrates/init.py", line 17, in
from tensorflow_probability.python.internal import all_util
File "/usr/local/lib/python3.8/dist-packages/tensorflow_probability/python/init.py", line 138, in
dir(globals()[pkg_name]) # Forces loading the package from its lazy loader.
File "/usr/local/lib/python3.8/dist-packages/tensorflow_probability/python/internal/lazy_loader.py", line 57, in dir
module = self._load()
File "/usr/local/lib/python3.8/dist-packages/tensorflow_probability/python/internal/lazy_loader.py", line 37, in _load
self._on_first_access()
File "/usr/local/lib/python3.8/dist-packages/tensorflow_probability/python/init.py", line 59, in _validate_tf_environment
raise ImportError(
ImportError: This version of TensorFlow Probability requires TensorFlow version >= 2.13; Detected an installation of version 2.9.0. Please upgrade TensorFlow to proceed.

Could you please advise me on how to resolve this issue?
Thank you very much for your assistance!

**Comment by TillBeemelmanns** [comment]
I added the line

```
tensorflow-probability==0.17.0
```

to `requirements.txt`. It should work now.
